# Generated by Django 5.2.15 on 2026-06-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='IVA 10%, IVA 5%, Exento, etc.', max_length=50)),
                ('tasa_porcentaje', models.DecimalField(decimal_places=2, help_text='10.00 para IVA 10%', max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento', 'fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('COMBO', 'Combo'), ('KIT', 'Kit'), ('COMPUESTO', 'Producto Compuesto')], default='PRODUCTO', max_length=10)),
                ('codigo', models.CharField(help_text='Código interno del producto', max_length=30)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('codigo_barras', models.CharField(blank=True, max_length=50)),
                ('qr_data', models.CharField(blank=True, help_text='Contenido codificado en el QR (por defecto, el código interno)', max_length=255)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('precio', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('controla_lote', models.BooleanField(default=False)),
                ('controla_serie', models.BooleanField(default=False)),
                ('controla_vencimiento', models.BooleanField(default=False)),
                ('metodo_costeo', models.CharField(choices=[('FIFO', 'FIFO - Primero en entrar, primero en salir'), ('LIFO', 'LIFO - Último en entrar, primero en salir'), ('PROMEDIO', 'Promedio Ponderado')], default='PROMEDIO', max_length=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_seguridad', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
            options={
                'verbose_name': 'Componente de Producto',
                'verbose_name_plural': 'Componentes de Producto',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('DEFECTUOSO', 'Defectuoso')], default='DISPONIBLE', max_length=12)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='UN, KG, LT, MT, CJ, etc.', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('permite_decimales', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='companies.empresa')),
                ('parent', models.ForeignKey(blank=True, help_text='Dejar vacío si es una categoría raíz; completar para que sea una subcategoría', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
    ]
