# Generated by Django 5.2.15 on 2026-06-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='suppliers.proveedor'),
        ),
        migrations.AddField(
            model_name='marca',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.impuesto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_costo', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda_precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_precio', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='suppliers.proveedor'),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='products.producto'),
        ),
        migrations.AddField(
            model_name='productocomponente',
            name='producto_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_combos', to='products.producto'),
        ),
        migrations.AddField(
            model_name='productocomponente',
            name='producto_padre',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ('COMBO', 'KIT', 'COMPUESTO')}, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='products.producto'),
        ),
        migrations.AddField(
            model_name='serie',
            name='deposito_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='companies.deposito'),
        ),
        migrations.AddField(
            model_name='serie',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='products.lote'),
        ),
        migrations.AddField(
            model_name='serie',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='products.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.unidadmedida'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'parent', 'nombre'), name='unique_categoria_por_empresa_y_parent', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_marca_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_lote'), name='unique_lote_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='productocomponente',
            constraint=models.UniqueConstraint(fields=('producto_padre', 'producto_componente'), name='unique_componente_por_padre'),
        ),
        migrations.AddConstraint(
            model_name='serie',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_serie'), name='unique_serie_por_producto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'sku'], name='products_pr_empresa_b71349_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'codigo_barras'], name='products_pr_empresa_22606d_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_producto_codigo_por_empresa'),
        ),
    ]
