# Generated by Django 5.2.15 on 2026-06-21 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 4217 (PYG, USD, BRL, ARS)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(help_text='Ej: ₲, $, R$', max_length=5)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='0 para PYG (no usa decimales), 2 para USD/BRL/ARS')),
                ('is_base', models.BooleanField(default=False, help_text='Marca la moneda base del sistema. Solo puede haber una.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_base', models.DecimalField(decimal_places=6, help_text='Cuántas unidades de la moneda base (PYG) equivale 1 unidad de esta moneda', max_digits=18)),
                ('effective_date', models.DateField(help_text='Fecha desde la cual esta tasa está vigente')),
                ('source', models.CharField(choices=[('MANUAL', 'Carga manual'), ('IMPORTADO', 'Importado (Excel/CSV)')], default='MANUAL', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='currencies.currency')),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_loaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-effective_date', 'currency'],
                'indexes': [models.Index(fields=['currency', '-effective_date'], name='currencies__currenc_f1b825_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'effective_date'), name='unique_currency_rate_per_day')],
            },
        ),
    ]
