# Generated by Django 5.2.15 on 2026-06-21 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoWebItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Ítem de Pedido Web',
                'verbose_name_plural': 'Ítems de Pedido Web',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=22)),
                ('estado_nuevo', models.CharField(max_length=22)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Pedido',
                'verbose_name_plural': 'Historial de Estados de Pedido',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (carrito)'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('VALIDADO', 'Validado (stock reservado)'), ('RECHAZADO', 'Rechazado'), ('APROBADO', 'Aprobado'), ('EN_PICKING', 'En picking'), ('FACTURADO', 'Facturado'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=22)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='customers.cliente')),
            ],
            options={
                'verbose_name': 'Pedido Web',
                'verbose_name_plural': 'Pedidos Web',
                'ordering': ['-fecha_pedido'],
            },
        ),
    ]
