# Generated by Django 5.2.15 on 2026-06-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('companies', '0001_initial'),
        ('customer_portal', '0001_initial'),
        ('orders', '0001_initial'),
        ('pricing', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_web', to='pricing.cupon'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='deposito_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='companies.deposito'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='documento_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='billing.documentoventa'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_web', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='lista_precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_web', to='pricing.listaprecio'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='portal_user',
            field=models.ForeignKey(blank=True, help_text='Quién creó el pedido desde el portal (nulo si lo creó un usuario interno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to='customer_portal.portaluser'),
        ),
        migrations.AddField(
            model_name='pedidoweb',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_web', to='companies.sucursal'),
        ),
        migrations.AddField(
            model_name='historialestadopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='orders.pedidoweb'),
        ),
        migrations.AddField(
            model_name='pedidowebitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pedidoweb'),
        ),
        migrations.AddField(
            model_name='pedidowebitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.producto'),
        ),
    ]
