# Generated by Django 5.2.15 on 2026-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoweb',
            name='prioridad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Puede asignarla el Módulo 16 (motor de reglas) automáticamente, ej. para clientes VIP', max_length=10),
        ),
    ]
