# Generated by Django 5.2.15 on 2026-06-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precio', to='companies.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_precio', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='pricing.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_lista', to='products.producto')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Producto',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='products.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='companies.empresa')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='products.producto')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Descuento porcentual'), ('MONTO_FIJO', 'Monto fijo')], default='PORCENTAJE', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo en la moneda del pedido', max_digits=18)),
                ('monto_minimo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_cupon_codigo_por_empresa')],
            },
        ),
        migrations.AddConstraint(
            model_name='listaprecio',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_lista_precio_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='precioproducto',
            constraint=models.UniqueConstraint(fields=('lista_precio', 'producto'), name='unique_precio_por_lista_y_producto'),
        ),
    ]
