# Generated by Django 5.2.15 on 2026-06-21 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(help_text='RUC, CI o documento del exterior', max_length=20)),
                ('tipo_contribuyente', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica'), ('EXTRANJERO', 'Cliente del Exterior')], default='FISICA', max_length=12)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dias_credito', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='companies.empresa')),
                ('moneda_default', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'ruc'), name='unique_cliente_ruc_por_empresa')],
            },
        ),
    ]
