# Generated by Django 5.2.15 on 2026-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_vip',
            field=models.BooleanField(default=False, help_text='Usado por el Módulo 16 (motor de reglas) para priorizar sus pedidos automáticamente'),
        ),
    ]
