# Generated by Django 5.2.15 on 2026-06-21 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa principal del usuario. Nulo solo para superusuarios globales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='sucursal_actual',
            field=models.ForeignKey(blank=True, help_text='Sucursal activa en la sesión actual del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos_aqui', to='companies.sucursal'),
        ),
        migrations.AddField(
            model_name='user',
            name='sucursales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales a las que este usuario tiene acceso autorizado', related_name='usuarios_con_acceso', to='companies.sucursal'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.sucursal'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfabackupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Nulo = aplica a todas las empresas del usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Nulo = aplica a todas las sucursales permitidas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='companies.sucursal'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='accounts_au_model_n_76c60d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_b490c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['email_attempted', '-timestamp'], name='accounts_lo_email_a_b49201_idx'),
        ),
    ]
