# Generated by Django 5.2.15 on 2026-06-21 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ALMACEN', 'Almacén'), ('TRANSITO', 'Tránsito'), ('DEVOLUCION', 'Devoluciones'), ('CENTRO_DISTRIBUCION', 'Centro de Distribución')], default='ALMACEN', max_length=25)),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Dirección física si difiere de la sucursal', max_length=255)),
                ('permite_venta_directa', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['sucursal', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC / Identificación fiscal')),
                ('tipo_contribuyente', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='JURIDICA', max_length=10)),
                ('timbrado_numero', models.CharField(blank=True, max_length=20)),
                ('timbrado_vencimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moneda_default', models.ForeignKey(help_text='Moneda en la que esta empresa emite presupuestos/facturas por defecto', on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('es_casa_matriz', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['empresa', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('establecimiento', models.CharField(help_text='Código de establecimiento SET', max_length=3)),
                ('punto_expedicion', models.CharField(help_text='Código de punto de expedición SET', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposito_predeterminado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='companies.deposito')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_venta', to='companies.sucursal')),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'ordering': ['sucursal', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='deposito',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='companies.sucursal'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_sucursal_codigo_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='puntoventa',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='unique_pv_codigo_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='deposito',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='unique_deposito_codigo_por_sucursal'),
        ),
    ]
