# Generated by Django 5.2.15 on 2026-06-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito'), ('PRESUPUESTO', 'Presupuesto'), ('REMISION', 'Remisión')], max_length=15)),
                ('numero', models.CharField(help_text='Formato establecimiento-puntoExp-secuencial', max_length=20)),
                ('tipo_cambio_pyg', models.DecimalField(decimal_places=6, default=1, help_text='Tasa de cambio a PYG vigente al momento de la emisión (snapshot inmutable)', max_digits=18)),
                ('condicion_venta', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10)),
                ('afecta_inventario', models.BooleanField(default=False, help_text='Si está marcado, al emitir el documento se descuenta (o repone, en NC) stock real')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_pyg', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, help_text='Solo relevante para FACTURA con condición CREDITO; Tesorería (fase posterior) lo actualiza con los cobros', max_digits=18)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de Venta',
                'verbose_name_plural': 'Documentos de Venta',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Snapshot del nombre del producto al momento de la venta', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, help_text='Precio neto, sin impuesto', max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tasa_impuesto_aplicada', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot de la tasa al momento de la venta', max_digits=5)),
                ('subtotal_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuesto_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Ítem de Documento de Venta',
                'verbose_name_plural': 'Ítems de Documento de Venta',
            },
        ),
        migrations.CreateModel(
            name='SecuenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=15)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Documento',
                'verbose_name_plural': 'Secuencias de Documento',
            },
        ),
    ]
