# Generated by Django 5.2.15 on 2026-06-21 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0002_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_venta', to='customers.cliente'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='deposito_salida',
            field=models.ForeignKey(blank=True, help_text='Obligatorio si afecta_inventario=True', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_venta', to='companies.deposito'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='documento_referencia',
            field=models.ForeignKey(blank=True, help_text='Factura que afecta esta NC/ND, o factura/presupuesto de origen de esta Remisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_relacionados', to='billing.documentoventa'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_venta', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_venta', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_venta', to='companies.puntoventa'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_venta', to='companies.sucursal'),
        ),
        migrations.AddField(
            model_name='documentoventa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_venta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoventaitem',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.documentoventa'),
        ),
        migrations.AddField(
            model_name='documentoventaitem',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.impuesto'),
        ),
        migrations.AddField(
            model_name='documentoventaitem',
            name='movimiento_inventario',
            field=models.ForeignKey(blank=True, help_text='Movimiento de stock generado por esta línea, si el documento afecta inventario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='documentoventaitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.producto'),
        ),
        migrations.AddField(
            model_name='secuenciadocumento',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_documento', to='companies.puntoventa'),
        ),
        migrations.AddIndex(
            model_name='documentoventa',
            index=models.Index(fields=['empresa', 'tipo_documento', '-fecha_emision'], name='billing_doc_empresa_d977c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoventa',
            index=models.Index(fields=['cliente', '-fecha_emision'], name='billing_doc_cliente_16f01b_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentoventa',
            constraint=models.UniqueConstraint(fields=('punto_venta', 'tipo_documento', 'numero'), name='unique_numero_por_pv_y_tipo'),
        ),
        migrations.AddConstraint(
            model_name='secuenciadocumento',
            constraint=models.UniqueConstraint(fields=('punto_venta', 'tipo_documento'), name='unique_secuencia_por_pv_y_tipo'),
        ),
    ]
