# Generated by Django 5.2.15 on 2026-06-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoventa',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento adicional a nivel de documento (ej. cupón), aplicado después de impuestos. No se redistribuye proporcionalmente entre líneas ni recalcula el IVA por línea.', max_digits=18),
        ),
    ]
