# Generated by Django 5.2.15 on 2026-06-21 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCopiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('intent_detectado', models.CharField(blank=True, max_length=50)),
                ('respuesta_resumen', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_copiloto', to='companies.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_copiloto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta al Copiloto',
                'verbose_name_plural': 'Consultas al Copiloto',
                'ordering': ['-fecha'],
            },
        ),
    ]
