# Generated by Django 5.2.15 on 2026-06-21 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_documentoventa_descuento_global'),
        ('companies', '0001_initial'),
        ('inventory', '0003_stockreserva'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=12)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_picking', to='companies.deposito')),
                ('pedido_web', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_picking', to='orders.pedidoweb')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_picking_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Picking',
                'verbose_name_plural': 'Órdenes de Picking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenPacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_bultos', models.PositiveIntegerField(default=1)),
                ('peso_total_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen_total_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden_picking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing', to='logistics.ordenpicking')),
            ],
            options={
                'verbose_name': 'Orden de Packing',
                'verbose_name_plural': 'Órdenes de Packing',
            },
        ),
        migrations.CreateModel(
            name='OrdenPickingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pickeada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('orden_picking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.ordenpicking')),
                ('pedido_web_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.pedidowebitem')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.ubicacion')),
            ],
            options={
                'verbose_name': 'Ítem de Picking',
                'verbose_name_plural': 'Ítems de Picking',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('PROPIO', 'Flota propia'), ('TERCERIZADO', 'Tercerizado')], default='PROPIO', max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportistas', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidad_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='logistics.transportista')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('conductor_nombre', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('PARCIAL', 'Entregado parcialmente')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='companies.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_creados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='logistics.ruta')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='logistics.transportista')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='logistics.vehiculo')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha_despacho'],
            },
        ),
        migrations.CreateModel(
            name='DespachoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_entrega', models.PositiveSmallIntegerField(default=1, help_text='Orden de visita dentro de la ruta')),
                ('direccion_entrega', models.CharField(blank=True, max_length=255)),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Entrega fallida')], default='PENDIENTE', max_length=12)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('firma_recibido', models.CharField(blank=True, help_text='Nombre de quién recibió la mercadería', max_length=150)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='logistics.despacho')),
                ('documento_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='billing.documentoventa')),
            ],
            options={
                'verbose_name': 'Documento en Despacho',
                'verbose_name_plural': 'Documentos en Despacho',
                'ordering': ['despacho', 'orden_entrega'],
                'constraints': [models.UniqueConstraint(fields=('despacho', 'documento_venta'), name='unique_documento_por_despacho')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('transportista', 'placa'), name='unique_vehiculo_placa_por_transportista'),
        ),
    ]
