# Generated by Django 5.2.15 on 2026-06-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('ruc', models.CharField(max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='companies.empresa')),
                ('moneda_default', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'ruc'), name='unique_proveedor_ruc_por_empresa')],
            },
        ),
    ]
