# Generated by Django 5.2.15 on 2026-06-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('TRANSFERENCIA_SALIDA', 'Transferencia (salida)'), ('TRANSFERENCIA_ENTRADA', 'Transferencia (entrada)'), ('CONTEO_AJUSTE', 'Ajuste por conteo físico')], max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Siempre positiva; el signo lo da tipo_movimiento', max_digits=18)),
                ('costo_unitario_pyg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('costo_total_pyg', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_cantidad_posterior', models.DecimalField(decimal_places=4, max_digits=18)),
                ('saldo_valor_posterior_pyg', models.DecimalField(decimal_places=2, max_digits=18)),
                ('grupo_transferencia', models.UUIDField(blank=True, default=None, null=True)),
                ('documento_tipo', models.CharField(blank=True, max_length=50)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario (Kardex)',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('costo_promedio_pyg', models.DecimalField(decimal_places=6, default=0, help_text='Costo unitario promedio en PYG. Para FIFO/LIFO es informativo (valor total de capas vigentes / cantidad); para PROMEDIO es el costo real usado.', max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo de Stock',
                'verbose_name_plural': 'Saldos de Stock',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código compuesto, ej: A-01-03', max_length=20)),
                ('rack', models.CharField(blank=True, max_length=20)),
                ('pasillo', models.CharField(blank=True, max_length=20)),
                ('estanteria', models.CharField(blank=True, max_length=20)),
                ('nivel', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['deposito', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CapaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_original', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_disponible', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario_pyg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fecha_ingreso', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas_costo', to='companies.deposito')),
            ],
            options={
                'verbose_name': 'Capa de Costo',
                'verbose_name_plural': 'Capas de Costo',
                'ordering': ['fecha_ingreso'],
            },
        ),
    ]
