# Generated by Django 5.2.15 on 2026-06-21 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capacosto',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capas_costo', to='products.lote'),
        ),
        migrations.AddField(
            model_name='capacosto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas_costo', to='products.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='companies.deposito'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='products.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='products.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacosto',
            name='movimiento_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capas_generadas', to='inventory.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='companies.deposito'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='products.lote'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='products.producto'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='companies.deposito'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='capacosto',
            index=models.Index(fields=['producto', 'deposito', 'lote', 'fecha_ingreso'], name='inventory_c_product_bbd8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['producto', 'deposito'], name='inventory_s_product_b29c41_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('producto', 'deposito', 'lote'), name='unique_stock_balance_producto_deposito_lote', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('deposito', 'codigo'), name='unique_ubicacion_codigo_por_deposito'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'deposito', '-fecha'], name='inventory_m_product_931f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['grupo_transferencia'], name='inventory_m_grupo_t_b34819_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento', '-fecha'], name='inventory_m_tipo_mo_563633_idx'),
        ),
    ]
