# Generated by Django 5.2.15 on 2026-06-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('inventory', '0002_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('referencia_tipo', models.CharField(help_text='Ej: PEDIDO_WEB', max_length=50)),
                ('referencia_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='companies.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='products.producto')),
            ],
            options={
                'verbose_name': 'Reserva de Stock',
                'verbose_name_plural': 'Reservas de Stock',
                'indexes': [models.Index(fields=['producto', 'deposito', 'active'], name='inventory_s_product_e417a6_idx'), models.Index(fields=['referencia_tipo', 'referencia_id'], name='inventory_s_referen_7f61e5_idx')],
            },
        ),
    ]
