# Generated by Django 5.2.15 on 2026-06-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAutomatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo_entidad', models.CharField(choices=[('PRODUCTO', 'Producto'), ('PEDIDO_WEB', 'Pedido Web')], max_length=15)),
                ('evaluar_en', models.CharField(choices=[('AL_GUARDAR', 'Al crear/actualizar el registro'), ('PERIODICO', 'Periódicamente (Celery Beat)')], default='AL_GUARDAR', max_length=12)),
                ('frecuencia_horas', models.PositiveSmallIntegerField(default=24, help_text='Solo aplica si evaluar_en=PERIODICO')),
                ('condiciones', models.JSONField(help_text='Lista de condiciones (todas deben cumplirse - AND). Cada una: {"campo": "stock_actual", "operador": "<", "campo_comparacion": "stock_minimo"} o {"campo": "dias_sin_movimiento", "operador": ">", "valor": 180}')),
                ('accion', models.CharField(choices=[('GENERAR_SOLICITUD_COMPRA', 'Generar solicitud de compra'), ('GENERAR_ALERTA', 'Generar alerta'), ('ASIGNAR_PRIORIDAD', 'Asignar prioridad')], max_length=30)),
                ('parametros_accion', models.JSONField(blank=True, default=dict, help_text='Ej: {"prioridad": "ALTA"} para ASIGNAR_PRIORIDAD, {"mensaje": "..."} para GENERAR_ALERTA')),
                ('active', models.BooleanField(default=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_automatizacion', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Regla de Automatización',
                'verbose_name_plural': 'Reglas de Automatización',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('condicion_cumplida', models.BooleanField()),
                ('accion_ejecutada', models.BooleanField(default=False)),
                ('contexto_evaluado', models.JSONField(blank=True, default=dict)),
                ('resultado', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='automation.reglaautomatizacion')),
            ],
            options={
                'verbose_name': 'Ejecución de Regla',
                'verbose_name_plural': 'Ejecuciones de Regla',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='companies.empresa')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='automation.reglaautomatizacion')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', 'leida', '-fecha'], name='automation__empresa_24dd76_idx')],
            },
        ),
    ]
