# Generated by Django 5.2.15 on 2026-06-21 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveSmallIntegerField()),
                ('es_ganada', models.BooleanField(default=False)),
                ('es_perdida', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_pipeline', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Etapa de Pipeline',
                'verbose_name_plural': 'Etapas de Pipeline',
                'ordering': ['empresa', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('origen', models.CharField(blank=True, help_text='Referido, web, llamada fría, feria, etc.', max_length=100)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('CALIFICADO', 'Calificado'), ('DESCARTADO', 'Descartado'), ('CONVERTIDO', 'Convertido a Cliente')], default='NUEVO', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('fecha_conversion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_convertido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospecto_origen', to='customers.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectos', to='companies.empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('probabilidad_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='ABIERTA', max_length=10)),
                ('motivo_perdida', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='customers.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='companies.empresa')),
                ('etapa_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.etapapipeline')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='currencies.currency')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_asignadas', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('EMAIL', 'Email'), ('REUNION', 'Reunión'), ('WHATSAPP', 'WhatsApp'), ('NOTA', 'Nota')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_proxima_accion', models.DateTimeField(blank=True, help_text='Para seguimiento: cuándo volver a contactar', null=True)),
                ('completada', models.BooleanField(default=True, help_text='False si es un seguimiento programado a futuro, aún pendiente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='customers.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='companies.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to=settings.AUTH_USER_MODEL)),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to='crm.oportunidad')),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_principal', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='customers.cliente')),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.AddConstraint(
            model_name='etapapipeline',
            constraint=models.UniqueConstraint(fields=('empresa', 'orden'), name='unique_orden_etapa_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='oportunidad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', False), ('prospecto__isnull', True)), models.Q(('cliente__isnull', True), ('prospecto__isnull', False)), _connector='OR'), name='oportunidad_pertenece_a_cliente_o_prospecto_exclusivo'),
        ),
        migrations.AddIndex(
            model_name='interaccion',
            index=models.Index(fields=['cliente', '-fecha'], name='crm_interac_cliente_40c111_idx'),
        ),
        migrations.AddIndex(
            model_name='interaccion',
            index=models.Index(fields=['prospecto', '-fecha'], name='crm_interac_prospec_1446c9_idx'),
        ),
        migrations.AddIndex(
            model_name='interaccion',
            index=models.Index(fields=['fecha_proxima_accion'], name='crm_interac_fecha_p_4ea96c_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', False), ('prospecto__isnull', True)), models.Q(('cliente__isnull', True), ('prospecto__isnull', False)), _connector='OR'), name='contacto_pertenece_a_cliente_o_prospecto_exclusivo'),
        ),
    ]
