# Generated by Django 5.2.15 on 2026-06-21 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='companies.empresa')),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to='companies.puntoventa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='companies.sucursal')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['sucursal', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to='currencies.currency')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='treasury.caja')),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_contado_efectivo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_esperado_efectivo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('apertura_caja', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='treasury.aperturacaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja (Arqueo)',
                'verbose_name_plural': 'Cierres de Caja (Arqueos)',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Cuenta Corriente'), ('AHORRO', 'Caja de Ahorro')], default='CORRIENTE', max_length=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('active', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='treasury.banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='companies.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='currencies.currency')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA_ENTRADA', 'Transferencia recibida'), ('TRANSFERENCIA_SALIDA', 'Transferencia enviada')], max_length=25)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='treasury.cuentabancaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('concepto', models.CharField(choices=[('COBRO_FACTURA', 'Cobro de factura'), ('PAGO_PROVEEDOR', 'Pago a proveedor'), ('GASTO', 'Gasto'), ('RETIRO', 'Retiro'), ('DEPOSITO_BANCO', 'Depósito a banco'), ('OTRO', 'Otro')], max_length=20)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('QR', 'QR'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia_tipo', models.CharField(blank=True, help_text='Ej: DOCUMENTO_VENTA, FACTURA_PROVEEDOR', max_length=50)),
                ('referencia_id', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('apertura_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='treasury.aperturacaja')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='currencies.currency')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='unique_caja_codigo_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='aperturacaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja',), name='unique_apertura_activa_por_caja'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(fields=('banco', 'numero_cuenta'), name='unique_cuenta_por_banco'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['apertura_caja', 'tipo'], name='treasury_mo_apertur_834889_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['referencia_tipo', 'referencia_id'], name='treasury_mo_referen_2692a0_idx'),
        ),
    ]
