# Generated by Django 5.2.15 on 2026-06-21 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
        ('inventory', '0002_initial'),
        ('products', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número de cotización del proveedor, si tiene', max_length=30)),
                ('plazo_entrega_dias', models.PositiveSmallIntegerField(default=0)),
                ('condiciones_pago', models.CharField(blank=True, max_length=150)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('SELECCIONADA', 'Seleccionada'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='companies.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='currencies.currency')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='suppliers.proveedor')),
            ],
            options={
                'verbose_name': 'Cotización de Compra',
                'verbose_name_plural': 'Cotizaciones de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.producto')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('condiciones_pago', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al proveedor'), ('CONFIRMADA', 'Confirmada por el proveedor'), ('RECIBIDA_PARCIAL', 'Recibida parcialmente'), ('RECIBIDA_TOTAL', 'Recibida totalmente'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='purchases.cotizacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='companies.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='currencies.currency')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='suppliers.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='companies.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.producto')),
            ],
            options={
                'verbose_name': 'Ítem de Orden de Compra',
                'verbose_name_plural': 'Ítems de Orden de Compra',
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_compra', to='companies.deposito')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='purchases.ordencompra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('numero_lote', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('movimiento_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.movimientoinventario')),
                ('orden_compra_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='purchases.ordencompraitem')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.recepcioncompra')),
            ],
            options={
                'verbose_name': 'Ítem de Recepción',
                'verbose_name_plural': 'Ítems de Recepción',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CONVERTIDA', 'Convertida en Orden de Compra')], default='BORRADOR', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_compra', to='companies.empresa')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_compra', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_compra', to='companies.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud de Compra',
                'verbose_name_plural': 'Solicitudes de Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='purchases.solicitudcompra'),
        ),
        migrations.CreateModel(
            name='SolicitudCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.solicitudcompra')),
            ],
            options={
                'verbose_name': 'Ítem de Solicitud de Compra',
                'verbose_name_plural': 'Ítems de Solicitud de Compra',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=30)),
                ('timbrado_proveedor', models.CharField(blank=True, max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('PAGADA_PARCIAL', 'Pagada parcialmente'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='companies.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedor', to='currencies.currency')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='suppliers.proveedor')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_proveedor', to='purchases.ordencompra')),
            ],
            options={
                'verbose_name': 'Factura de Proveedor',
                'verbose_name_plural': 'Facturas de Proveedor',
                'ordering': ['-fecha_emision'],
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'numero_factura'), name='unique_factura_proveedor_numero')],
            },
        ),
    ]
